name: Docker Build Check

# 當有代碼 push 到 main 分支時，觸發這個動作
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest # 在雲端開一台 Linux 電腦
    steps:
      - name: 複製程式碼
        uses: actions/checkout@v4

      - name: 嘗試打包 Docker Image
        run: docker build -t test-image .